config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  resources :users, only: [:show] do
    resources :posts, only: [:new, :create, :index, :show] do
      resources :comments, only: [:new, :create]
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role == 'admin'
      can :manage, :all
    else
      can :destroy, Post do |post|
        post.author == user
      end
      can :destroy, Comment do |comment|
        comment.author == user
      end
      can :create, Post
      can :create, Comment
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  def update_comments_counter
    post.increment!(:comment_counter)
  end

  def decrement_comments_counter
    post.decrement!(:comment_counter)
  end

  after_save :update_comments_counter
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  def update_likes_counter
    post.increment!(:likes_counter)
  end
  after_save :update_likes_counter
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, foreign_key: 'post_id'
  has_many :likes, foreign_key: 'post_id'
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comment_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def decrement_posts_counter
    author.decrement!(:post_counter)
  end

  def update_posts_counter
    author.increment!(:post_counter)
  end
  after_save :update_posts_counter
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'

  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include WillPaginate::ViewHelpers
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def new
    @comments = Comment.new
  end

  def create
    @current_post = Post.find(params[:post_id])
    @comments = @current_post.comments.new(comment_params)
    @comments.post_id = @current_post.id
    @comments.author_id = current_user.id

    if @comments.save
      redirect_to "/users/#{@current_post.author_id}/posts/#{@current_post.id}"
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comments = @post.comments.find(params[:id])
    @comments.destroy

    if @comments.destroy
      @comments.decrement_comments_counter
      redirect_to user_post_path(@post.author_id, @post.id)
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(author_id: current_user.id, post_id: @post.id)

    if @like.save
      redirect_to "/users/#{@post.author_id}/posts/#{@post.id}"
    else
      render.new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.includes(:posts).find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @posts = Post.includes(:comments).find(params[:id])
    @comments = @posts.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to "/users/#{current_user.id}/posts"
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.comments.destroy_all
    @post.likes.destroy_all
    @post.destroy

    if @post.destroy
      @post.decrement_posts_counter
      redirect_to user_posts_path(current_user.id)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.includes(posts: %i[comments likes]).find(params[:id])
    @posts = @user.posts
  end

  def index
    @users = User.includes(:posts)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_controller_helper.rb
module CommentsControllerHelper
end

app/helpers/likes_controller_helper.rb
module LikesControllerHelper
end

app/views/comments/new.html.erb
<div class='mt-5 d-flex align-items-center flex-column'>
  <h1>Enter your comment below: </h1>
  <%= form_with model: @comments, url: user_post_comments_path do |f| %>
    <div class='mb-3'>
      <%= f.text_area :text, size:"50x3",placeholder: 'Enter Your Comment', class:'form-control'%>
    </div>
    <%= f.submit "Comment", class:'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "devise" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="d-flex align-items-center justify-content-center" >
  <div>
    <div class="card mb-3 text-center d-flex justify-content-center" style="width: 800px;">
      <div class="row g-0 text-center">
        <div class="col-md-4">
          <img src="<%= @user.photo %>" class="img-fluid rounded-start" alt="profile">
        </div>
        <div class="col-md-8">
          <div class="card-body d-flex flex-column">
  <div class="text-start mt-5">
    <h4 class="card-title"><%= @user.name %></h4>
  </div>
  <div class="text-end mt-5">
    <p class="card-text"><h6>Number of posts: <%= @user.post_counter %></h6></p>
  </div>
</div>
        </div>
      </div>
    </div>
    
    <%= link_to "Add New Post", new_user_post_path(user_id: @user.id), class:"btn btn-primary my-3" %>
    <h4>Posts</h4>
    
    <% @posts.each do |post| %>
      <%= link_to user_post_path(user_id: @user.id, id: post.id), class:"nav-link mt-4 d-flex justify-content-center" do %>
        <div class="card mb-3 text-center justify-content-center" style="width: 800px;">
          <div class="row g-0 text-center">
            <div class="col-md-8">
              <div class="card-body d-flex justify-content-between align-items-center mb-2" style="width: 800px;">
                <div class="d-flex flex-column">
                  <h2 h2 class="card-title text-start"><%= post.title %></h2>
                  <h5 class="card-title"><%= post.text %></h5>
                </div>
                <div class ="align-self-end">
                <p class="card-text text-end"><span>Comments: <%= post.comment_counter %></span></p>
                </div>
              </div>
            </div>

              <% if post.recent_comments.empty? %>
            <div class="card mb-3 border-secondary" style="width: 800px;">
              <div class="card-body">
                <p class="card-text">No Comments</p>
              </div>
            </div>
          <% else %>
            <div class="card mb-3 border-secondary" style="width: 800px;">
              <div class="card-body">
                <% post.recent_comments.each do |comment| %>
                  <p class="card-text"><%= comment.author.name %>: <%= comment.text %></p>
                <% end %>
              </div>
            </div>
          <% end %>
            </div>
          </div>
      <% end %>
    <% end %>

  </div>
</div>

app/views/posts/new.html.erb
<div class='mt-3 d-flex align-items-center flex-column'>
  <h1>Create New Post</h1>
  <%= form_with model: @post, url: user_posts_path do |form| %>
    <div class="mb-3">
      <%= form.text_field :title, placeholder:"Enter Post Title", class:"form-control"%>
    </div>
    <div class="mb-3">
      <%= form.text_area :text, size:"70x6" ,placeholder:"Enter Your Post", class:"form-control" %>
    </div>
    <div class="mb-3">
      <%= form.submit "Add New Post", class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class='mt-3 d-flex align-items-center flex-column'>
  <div class="card mb-3 border-primary" style="width: 800px;">
    <div class="card-header bg-primary text-white">
      <div class='row'>
        <div class='col-md-8'><%= @posts.title %> by <%= @user.name %></div>
        <div class='col-md-4 d-flex gap-2'>
          <p class="card-text"><small class="text-white">Comments: <%= @posts.comment_counter %></small></p>
          | 
          <p class="card-text"><small class="text-white">Likes: <%= @posts.likes_counter %></small></p>
        </div>
      </div>
    </div>
    <div class="card-body">
      <p class="card-text"><%= @posts.text%></p>
    </div>
  </div>
    <% if @comments.empty? %>
     <div class="card mb-3 border-secondary" style="width: 700px;">
       <div class="card-body">
            <p class="card-text">No Comments</p>
          </div>
        </div>
 <% else %>
     <div class="card mb-3 border-secondary" style="width: 700px;">
          <div class="card-body">
            <% @comments.each do |comment| %>
            <div class='d-flex justify-content-between align-items-center'>
              <p class="card-text"><%= comment.author.name %>: <%= comment.text %></p>
              <% if can? :destroy, comment %>
              <%= button_to "Delete", user_post_comment_path(@post.author, @posts, comment), method: :delete, class:"btn btn-outline-danger" %>
              <% end %>
              </div>
              <% end %>
          </div>
      </div>
      <% end %>
<div class="d-flex align-items-center justify-content-between" style="width:400px">

    <%= form_with model: @like, url: user_post_likes_path(post_id: @posts.id) do |f| %>
      <%= f.submit "Like", class:"btn btn-outline-primary" %>
    <% end %>
    <%= link_to "Add Comment", new_user_post_comment_path(@user.id, @posts.id), class:"btn btn-primary" %>

      <% if can? :destroy, @posts %>
        <%= button_to "Delete", user_post_path(id: @posts.id), method: :delete, class:"btn btn-outline-danger" %>
        <% end %>

</div>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Users</h1>

<% @users.each do |user| %>
  <%= link_to user_path(id: user.id), class: "nav-link mt-4 d-flex justify-content-center" do %>
    <div class="card mb-3 text-center" style="width: 800px;">
      <div class="row g-0 text-center">
        <div class="col-md-4">
        <img src="<%= user.photo %>" class="img-fluid rounded-start" alt="profile">
        </div>
        <div class="col-md-8">
          <div class="card-body d-flex flex-column">
            <div class="text-start mt-5">
              <h4 class="card-title"><%= user.name %></h4>
            </div>
            <div class="text-end mt-5">
              <h6 class="card-text">Number of posts: <%= user.post_counter %></h6>
            </div>
          </div>
        </div>
      </div>
    </div> 
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="d-flex justify-content-center">
<div class="card mb-3 text-center" style="width: 800px;">
  <div class="row g-0 text-center">
    <div class="col-md-4">
      <img src="<%= @user.photo %>" class="img-fluid rounded-start" alt="profile">
    </div>
    <div class="col-md-8">
      <div class="card-body d-flex flex-column">
  <div class="text-start mt-5">
    <h4 class="card-title"><%= @user.name %></h4>
  </div>
  <div class="text-end mt-5">
    <p class="card-text"><h6>Number of posts: <%= @user.posts.count %></h6></p>
  </div>
</div>
    </div>
  </div>
</div>
</div>
<div class="d-flex justify-content-center">
<div class="card mb-3 border-info" style="width: 800px;">
    <div class='card-header'>Bio</div>
    <div class="card-body">
      <p class="card-text"><%= @user.bio %></p>
    </div>
  </div>
   </div>
  <% if @user.recent_posts.empty? %>
  <div class="d-flex justify-content-center">
    <div class="card mb-3" style="width: 800px;">
      <div class="card-header ">No Posts</div>
      <div class="card-body">
        <h5 class="card-title">Please submit a new post.</h5>
      </div>
    </div>
  </div>
  <% else %>
    <% @user.recent_posts.each do |post| %>
      <%= link_to user_post_path(user_id:@user.id, id: post.id), class:'nav-link' do%>
      <div class="d-flex justify-content-center">
        <div class="card mb-3" style="width: 800px;">
          <div class="card-header"><%= post.title %></div>
          <div class="card-body">
            <h5 class="card-title"><%= post.text %></h5>
          </div>
          <div class='card-footer d-flex gap-2 justify-content-end'>
            <p class="card-text"><span class="text-muted">Comments: <%= post.comment_counter %></span></p>
            |
            <p class="card-text"><span class="text-muted">Likes: <%= post.likes_counter %></span></p>
          </div>
        </div>
        </div>
      <% end %>
    <% end %>
    
  <% end %>

<div class="d-flex justify-content-center">
  <%= link_to "See all posts", user_posts_path(user_id: @user.id), class:"btn btn-dark mb-3" %>
</div>